using FluentResults.Extensions.AspNetCore;
using LibraryManagement.Data;
using LibraryManagement.Helpers;
using LibraryManagement.Repository;
using LibraryManagement.Repository.Interfaces;
using LibraryManagement.Services.Contracts;
using LibraryManagement.Services.Implementation;
using Mapster;
using MapsterMapper;
using Scalar.AspNetCore;
using Microsoft.EntityFrameworkCore;

// Load environment variables from the .env file (used for the connection string, etc.)
DotNetEnv.Env.TraversePath().Load();

var builder = WebApplication.CreateBuilder(args);

// =====================================================
// MAPSTER (Object Mapping)
// =====================================================
// Mapster is used to map between entities and DTOs automatically.
var config = TypeAdapterConfig.GlobalSettings;
builder.Services.AddSingleton(config);
builder.Services.AddScoped<IMapper, ServiceMapper>();
builder.Services.AddMapster();

// =====================================================
// FLUENTRESULTS (Error Handling)
// =====================================================
// This gives access to the current HttpContext, needed to build proper HTTP responses.
builder.Services.AddHttpContextAccessor();

// Register our custom profile. It turns FluentResults errors (like NotFound, Conflict)
// into the correct HTTP status codes (404, 409, etc.) automatically.
builder.Services.AddSingleton<FluentResultsEndpointProfile>();

// =====================================================
// DATABASE
// =====================================================
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(connectionString));

// =====================================================
// API SERVICES
// =====================================================
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();

// Swagger generates the OpenAPI document (swagger.json). Scalar will use this
// same document to render the API reference UI.
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new Microsoft.OpenApi.OpenApiInfo
    {
        Title = "Library Management API",
        Version = "v1",
        Description = "API for managing categories and subcategories in a library system."
    });

    // This reads the XML file (generated by GenerateDocumentationFile) so Swagger/Scalar
    // can show the summary comments from the code as descriptions in the docs.
    var xmlFile = $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var path = Path.Combine(AppContext.BaseDirectory, xmlFile);
    options.IncludeXmlComments(path);
});

// =====================================================
// DEPENDENCY INJECTION: REPOSITORIES AND SERVICES
// =====================================================
builder.Services.AddScoped<IUnitWork, UnitWork>();
builder.Services.AddScoped(typeof(IRepository<>), typeof(Repository<>));
builder.Services.AddScoped<ICategoryRepository, CategoryRepository>();
builder.Services.AddScoped<ICategoryService, CategoryService>();
builder.Services.AddScoped<ISubCategoryRepository, SubCategoryRepository>();
builder.Services.AddScoped<ISubCategoryService, SubCategoryService>();

var app = builder.Build();

// =====================================================
// FLUENTRESULTS CONFIGURATION
// =====================================================
// Get the services we need from the DI container after the app is built.
var httpContextAccessor = app.Services.GetRequiredService<IHttpContextAccessor>();
var profile = app.Services.GetRequiredService<FluentResultsEndpointProfile>();

// Give the profile a way to reach the current HttpContext.
profile.SetHttpContextProvider(() => httpContextAccessor.HttpContext!);

// Tell FluentResults to use our custom profile whenever it converts
// a Result into an HTTP response.
AspNetCoreResult.Setup(options =>
{
    options.DefaultProfile = profile;
});

// =====================================================
// HTTP PIPELINE
// =====================================================
if (app.Environment.IsDevelopment())
{
    // Generates the swagger.json document at /swagger/v1/swagger.json
    app.UseSwagger();

    // Scalar reads that same swagger.json document to render the API reference page.
    app.MapScalarApiReference(options =>
    {
        options.Title = "library API";
        options.OpenApiRoutePattern = "/swagger/{documentName}/swagger.json";
        options.Theme = ScalarTheme.DeepSpace;
        options.Layout = ScalarLayout.Modern;
    });
}

// Print the Scalar UI URL in the console when the app starts, just for convenience.
app.Lifetime.ApplicationStarted.Register(() =>
{
    var url = app.Urls.FirstOrDefault() ?? "http://localhost:5063";
    Console.WriteLine($"👉 Scalar UI: {url}/scalar/v1");
});

app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();
app.Run();